print("My name is Shaheer Jamal.")
print("I was born and raised in Karachi.")
print("I'm currently a student at Sir Syed University.")
print("This semester, I'm excited about learning Programming Fundamentals.")
print("In my free time, I enjoy exploring new programming concepts.")
print("I find programming to be both challenging and rewarding.")
print("One of my goals is to excel in Python programming.")
print("I'm passionate about cybersecurity and its practical applications.")
print("I believe in continuous learning and skill development.")
print("I'm looking forward to gaining hands-on experience in the field.")
print("I aspire to contribute positively to the tech industry.")
print("Hello, and welcome to my journey in programming!")
